### ISSUE TITLE
Logo For Net Hesap

### ISSUE THREAD

**Issue by zularizal** [hakkikaancaliskan/NetHesap#1]
Hi @hakkikaancaliskan , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by hakkikaancaliskan** [comment]
I would be grateful. Thank you so much. I'm waiting your logo @zularizal.

**Comment by zularizal** [comment]
These is some logos that I have designed, the logo is inspired from the letter n and h from the initial Net Hesap. And the checklist icon that has the meaning of test scores.
What do you think? which one do you like?
if there is something you want to change, please let me know.

![logo](https://user-images.githubusercontent.com/38547278/42015959-b4062290-7ad3-11e8-8c90-0421c967879e.png)

**Comment by hakkikaancaliskan** [comment]
5th one looks good :) can you change color of 5th? It should be more dark.

**Comment by zularizal** [comment]
What color you like?

![logo2](https://user-images.githubusercontent.com/38547278/42020092-1a36eaa6-7ae1-11e8-9f81-3bc415bff687.png)

**Comment by hakkikaancaliskan** [comment]
https://drive.google.com/file/d/1y0ffT9vYytn6d95sPKHeJ-FPQbWJTcrd/view?usp=drivesdk
I think it should match with app.

**Comment by zularizal** [comment]
Like this?

![g5252](https://user-images.githubusercontent.com/38547278/42020797-1eefc9da-7ae3-11e8-8884-dd8b15a7f417.png)

**Comment by hakkikaancaliskan** [comment]
Yeah that's great.

**Comment by zularizal** [comment]
How about icon? Left or right?
![rect5303](https://user-images.githubusercontent.com/38547278/42021214-3a01657a-7ae4-11e8-8bf5-e4d117aa61c4.png)

**Comment by hakkikaancaliskan** [comment]
Right one.

**Comment by zularizal** [comment]
Okay, wait a minute I will upload this logo to the drive and make you a pull request.

**Comment by zularizal** [comment]
Hello, I already uploaded the logo to drive, this link

https://drive.google.com/open?id=1Bt-HaXDf2Eih2szf6nV0I1dDyi8QNnd8

And I've also sent a pull request for you, check this #2

**Comment by hakkikaancaliskan** [comment]
Thank you so much man. You're great.
